In [2]:
from PIL import Image
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix
import joblib
import numpy as np
import mnist

In [3]:
#Training
x_train = mnist.train_images()
y_train = mnist.train_labels()

x_test = mnist.test_images()
y_test = mnist.test_labels()

In [6]:
x_train = x_train.reshape((-1,28*28))
x_test = x_test.reshape((-1,28*28))

In [7]:
x_train = (x_train)/256
x_test = (x_test)/256

In [10]:
clf = MLPClassifier(solver="adam",activation="relu",hidden_layer_sizes=(70,70))

In [11]:
clf.fit(x_train,y_train)

MLPClassifier(hidden_layer_sizes=(70, 70))

In [12]:
prediction = clf.predict(x_test)

In [13]:
acc = confusion_matrix(y_test,prediction)

In [14]:
print(acc)

[[ 971    0    0    3    2    0    1    1    1    1]
 [   0 1124    3    1    0    0    2    1    4    0]
 [   1    0 1014    3    2    0    2    5    4    1]
 [   0    0    7  984    0    3    0    5    4    7]
 [   1    1    3    0  959    1    4    2    1   10]
 [   2    0    0   11    2  867    5    0    3    2]
 [   5    2    2    2    2    5  940    0    0    0]
 [   2    1    8    2    2    0    0 1006    1    6]
 [   3    0    3    8    4    6    4    2  940    4]
 [   1    3    0    3    6    6    1    3    6  980]]


In [15]:
def accuracy(cm):
  diagonal = cm.trace()
  ele = cm.sum()
  return diagonal/ele

In [16]:
result = accuracy(acc)

In [17]:
print(result) #accuracy

0.9785


In [18]:
joblib.dump(clf,"model.sav")

['model.sav']